### PR TITLE
Support Snapshot HTTP API

### PR DESCRIPTION
**Pull request by yfouquet**
Following issue #314, add support for Snapshot HTTP API:
 - save snapshot in a file
 - restore snapshot from a file

### CODE REVIEW

**Comment by yfouquet** [comment]
Hi @IvannKurchenko,
Would this match your needs?

**Comment by IvannKurchenko** [comment]
Hello, @yfouquet !

Wow, Thank you so much for a such quick implementation. 
Looks really good, but from my point of view, it would be more flexable to return `InputStream` as resuls of `save` method instead of using `File destinationFile` argument - so lib clients can decide how to store/handle snapshot on their side. And same for `restore` - Can `InputStream` be passed instead of `File sourceFile` argument? I might be wrong, because not really expert in Retrofit lib. What do you think?

Thank you very much for a help!

Regards,
Ivan!

**Comment by yfouquet** [comment]
Hi @IvannKurchenko,

Thanks for your feedback. I first tried to use `InputStream` but it wasn't handy with retrofit.
I'll give a second look this evening.

Regards,

**Comment by IvannKurchenko** [comment]
Hello, @yfouquet!

Thanks - that was just an idea for improvement, if it will take extra effort to implement I don't think it worth it. I'm happy with changes you made.
Thank you so much for a help!

Regards,
Ivan!

**Comment by yfouquet** [comment]
After further checks, the use of InputStream is currently not possible with okhttp, see:
- https://github.com/square/okhttp/pull/1038
- https://github.com/square/okhttp/issues/2424

I'll merge this one as it is a working solution and i'll come back to it once okhttp enables `InputStream` in `RequestBody`.

**Comment by yfouquet** [comment]
Finally, i pushed a PR to handle InputStream in okhttp: https://github.com/square/okhttp/pull/3912 :crossed_fingers:

**Pull request merged**
