### PR TITLE
Dont require knownleader

### PR DESCRIPTION
**Pull request by chrisgray-vertex**
According to https://github.com/hashicorp/consul/issues/9776, the ```X-Consul-Knownleader``` is unreliable and is likely to be removed at some point.  In current versions of Consul, the value will be false when doing streaming requests.  This causes caches to get stale here.  

The recommendation from the referenced issue is to not use the ```X-Consul-Knownleader:``` for anything.

### CODE REVIEW

**Comment by windonis** [comment]
Hi all,

We need these commits. I wonder that, when will this commit be included in a tag?

Best Regards

**Comment by vbashko** [comment]
Not a Contribution.

Hi @rickfast, @chrisgray-vertex. It seems that the master build failed after this PR was merged and the change was never released to the maven central repo. Is there a way to re-build the project and release the library including this change?

Thanks!

**Comment by aswingit** [comment]
@rickfast @chrisgray-vertex Looks like the master build has failed after this PR was merged. Could you please review it? Observing that the "ServiceHealthCache" listener is not getting invoked as consuleResponse.isKnownLeader() is false in ConsulCache.onComplete()

**Comment by dlabey** [comment]
Any ETA on this?

**Comment by dlabey** [comment]
Any ETA for a release on this? Can you fix the build?

**Comment by dlabey** [comment]
@rickfast can you manually attempt to kick-off another Jenkins CI action from master?

**Pull request merged**
